---

# Installs pip, ipython and several basic packages

- name: Install packeges for basic-python
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
  tags: ["basic-python"]

- name: Install pip packages for basic-python
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ pip_packages }}"
  tags: ["basic-python"]