---

- block:
    - name: Clone YARA repo
      git:
        repo: "{{ yara_repo_url }}"
        dest: /opt/repo/yara
        force: yes
        update: yes
    
    - name: Bootstrap YARA
      shell: ./bootstrap.sh
      args:
        chdir: /opt/repo/yara

    - name: Configure YARA
      shell: ./configure --enable-magic
      args:
        chdir: /opt/repo/yara

    - name: Build YARA
      make:
        chdir: /opt/repo/yara

  become: false

- name: Install YARA
  make:
    chdir: /opt/repo/yara
    target: install

- name: Clone YARA-rules
  git:
    repo: "{{ yara_rules_repo_url }}"
    dest: /opt/repo/yara-rules
    force: yes
    update: yes
  become: false