---

- name: Clone z3 repo
  git:
    repo: "{{ z3_repo_url }}"
    dest: /opt/repo/z3
    force: yes
    version: z3-4.5.0
    update: yes
  become: false
  tags: ["z3-update"]

- name: Configure build for z3
  command: python scripts/mk_make.py --python
  args:
    chdir: /opt/repo/z3
  become: false
  tags: ["z3-update"]

- name: Build z3
  make:
    chdir: /opt/repo/z3/build
  become: false
  tags: ["z3-update"]

- name: Remove if previous symlink exists for libz3.so (it breaks make install)
  file:
    path: /usr/lib/python2.7/dist-packages/z3/lib/libz3.so
    state: absent

- name: Install z3
  make:
    chdir: /opt/repo/z3/build
    target: install
  tags: ["z3-update"]
