---

- name: Install packeges for basic-dev
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: Prepare /opt/repo folder
  file:
    path: /opt/repo
    state: directory
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: 0755
