---

packages:
    - python
    - python-pip
    - python-dev
    - ipython
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev   # used for compiling libs that use -lz

pip_packages:
    - Cython
    - lxml
    - requests