---

- name: Clone Radare2 repo
  git:
    repo: "{{ radare2_repo_url }}"
    dest: /opt/repo/radare2
    force: yes
    update: yes
  become: false
  tags: ["r2-update"]

- name: Build and install Radare2 by its sys/install.sh
  shell: sys/install.sh
  args:
    chdir: /opt/repo/radare2
  tags: ["r2-update"]

- name: Get back repo files owner
  file: 
    dest: /opt/repo/radare2 
    owner: "{{ ansible_user }}" 
    group: "{{ ansible_user }}" 
    recurse: yes
  tags: ["r2-update"]

- include: bindings.yml

- include: r2pm.yml