---

- name: Check if ansadm is present
  user:
    name: ansadm
    groups: sudo
    shell: /bin/bash
    state: present

- name: Remove password promnt for users in sudo group
  lineinfile:
    dest: "/etc/sudoers"
    regexp: "(%sudo\\s+ALL\\s*=\\s*NOPASSWD\\s*:\\s*ALL)|(%sudo\\s+ALL\\s*=\\s*\\(ALL\\)\\s*NOPASSWD\\s*:\\s*ALL)"
    line: "%sudo\tALL=(ALL) NOPASSWD:ALL"
    state: present

- name: Set SSH public key
  authorized_key:
    user: ansadm
    key: "{{ lookup('file', inventory_dir + '/keys/id_rsa.pub') }}"
    state: present

- name: Disable SSH login through password
  include: nopassauth.yml

