---

- name: Check if ansadm is present
  user:
    name: ansadm
    groups: sudo
    shell: /bin/bash
    state: present

- name: Set SSH public key
  authorized_key:
    user: ansadm
    key: "{{ lookup('file', inventory_dir + '/keys/id_rsa.pub') }}"
    state: present

- name: Disable SSH login through password
  include: nopassauth.yml

